{% set name = "entsoe-py" %}
{% set version = "0.5.10" %}
{% set sha256 = "7308f09df8e75d93a6a91d6c9a6970e697342c21d56dd3153c1c3facc5101f89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vvv '

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - beautifulsoup4
    - pandas
    - python >=3.6
    - pytz
    - requests
    - geojson-rewind
    - python-dateutil
    - geopandas

test:
  imports:
    - entsoe

about:
  home: https://github.com/EnergieID/entsoe-py
  license: MIT
  license_file: LICENSE
  summary: Python client for the ENTSO-E API (european network of transmission system operators for electricity)
  dev_url: https://github.com/EnergieID/entsoe-py

extra:
  recipe-maintainers:
    - FabianHofmann
