travis:
  secure:
    BINSTAR_TOKEN: uttw8jqfsLHYTYD62P+5RqPkO0obOg1Mqgq8lvUL1sfkF6bqEzLvT832bLQKJ8Ns1y//VcGkvgPvD/0g8zi35zzKJfNRAGBPu7K1N6+Sg0OCUNqrZMf9GQcghR10bB9VVPUH5EQucQN/W+IM9x9WyiTbkvXggeg2OOooj0+GZyO97IdHT61SAbvWfKtQRZh3ptzEu1AyIlHjj2f/+vUdO9FMlq+5txcIKm6WG+9otLSWkgxTnMSf1eghPc/yN8sF1AbE2y/+8OJ9iNWTZP8yMTeC+64pothM8braSUpQLlKTSBge2NNmy5NLACw6lloeGEyBU/5aaZ+hJA1w+M0i40uKpQ06aq2beFH3iPWTlq55K6bMg3SOefF/GUyxGs62AKGSublA7G0+bmWTqzbEMaWEeSp+jwUovc0e0DemsA4PAdSjfLLWpb9JHtOxTgxaEYiG2BIW126xJuIr9yyoP6QKBBzQTs7t1ocVjPEtxIAKpnQqlN3JWI2i1+XKmAcX0rgb4cv/ryfYJIa+Xl2UOWjoQzgPo2wzItMoLP0j6/7G8z/5QLJqaqsAqHSEK3tzYK45yLzfvlW2jWRB/sjWTXdAYQTDP99el9jwcb92qn1iJZNarudX+tF0MpXYh+eEinrAOEFeSiELZze9VlHlQT6Ciw9JbDt3GbA1nY0Jy20=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
